export default {
  info: {
    name: 'Ryu',
    game: 'Street Fighter III: Third Strike',
    health: 1200,
    stun: 64,
    taunt: 'Increase stun recovery',
    'forward dash': 13,
    'backward dash': 13,
    'normal wakeup': 77,
    'quick stand': 50,
  },
  moves: {
    normals: {
      'close jab': {
        name: 'st. LP (close)',
        damage: 30,
        stun: 3,
        startup: 3,
        active: 3,
        recovery: 5,
        'on block': 3,
        'on hit': 3,
        parry: 'High or Low',
        other: ['Special Cancelable', 'Super Cancelable']
      },
      'far jab': {
        name: 'st. LP (Far)',
        damage: 30,
        stun: 3,
        startup: 4,
        active: 3,
        recovery: 4,
        'on block': 4,
        'on hit': 4,
        parry: 'High or Low',
        other: ['Special Cancelable', 'Super Cancelable', 'Chain Cancelable']
      },
      'crouch lp': {
        name: 'cr. LP',
        damage: 15,
        stun: 3,
        startup: 4,
        active: 3,
        recovery: 5,
        'on block': 3,
        'on hit': 3,
        parry: 'High or Low',
        other: ['Special Cancelable', 'Super Cancelable', 'Chain Cancelable']
      },
      'close strong': {
        name: 'st. MP (close)',
        damage: 100,
        stun: 7,
        startup: 5,
        active: 4,
        recovery: 10,
        'on block': 14,
        'on hit': 5,
        parry: 'High',
        other: ['Special Cancelable', 'Super Cancelable']
      },
      'far strong': {
        name: 'st. MP (far)',
        damage: 100,
        stun: 11,
        startup: 5,
        active: 4,
        recovery: 9,
        'on block': 4,
        'on hit': 5,
        parry: 'High',
        other: ['Special Cancelable', 'Super Cancelable']
      },
      'crouching strong': {
        name: 'cr. MP',
        damage: 90,
        stun: 7,
        startup: 5,
        active: 4,
        recovery: 7,
        'on block': 3,
        'on hit': 4,
        parry: 'High or Low',
        other: ['Special Cancelable', 'Super Cancelable']
      },
      'close fierce': {
        name: 'st. HP (close)',
        damage: 130,
        stun: 15,
        startup: 4,
        active: 4,
        recovery: 17,
        'on block': -4,
        'on hit': -2,
        parry: 'High',
        other: ['Super Cancelable', 'Special Cancelable']
      },
      'far fierce': {
        name: 'st. HP (far)',
        damage: 130,
        stun: 13,
        startup: 11,
        active: 3,
        recovery: 18,
        'on block': -3,
        'on hit': -1,
        parry: 'High',
        other: []
      },
      'crouching fierce': {
        name: 'cr. HP',
        damage: 130,
        stun: 13,
        startup: 5,
        active: 5,
        recovery: 19,
        'on block': -8,
        'on hit': -6,
        parry: 'High or Low',
        other: ['Special Cancelable', 'Super Cancelable']
      },
      'standing short': {
        name: 'st. LK',
        damage: 40,
        stun: 3,
        startup: 4,
        active: 4,
        recovery: 7,
        'on block': 2,
        'on hit': 2,
        parry: 'High or Low',
        other: []
      },
      'couching short': {
        name: 'cr. LK',
        damage: 20,
        stun: 3,
        startup: 5,
        active: 3,
        recovery: 7,
        'on block': 1,
        'on hit': 1,
        parry: 'Low',
        other: ['Must be blocked low', 'Special Cancelable', 'Super Cancelable', 'Chain Cancelable']
      },
      'close standing forward': {
        name: 'st. MK (close)',
        damage: 110,
        stun: 11,
        startup: 4,
        active: 5,
        recovery: 11,
        'on block': 2,
        'on hit': 4,
        parry: 'High',
        other: ['Special Cancelable', 'Super Cancelable']
      },
      'far standing forward': {
        name: 'st. MK (far)',
        damage: 90,
        stun: 9,
        startup: 6,
        active: 4,
        recovery: 15,
        'on block': -5,
        'on hit': -4,
        other: []
      },
      'crouching forward': {
        name: 'cr. MK',
        damage: 80,
        stun: 3,
        startup: 7,
        active: 5,
        recovery: 16,
        'on block': -3,
        'on hit': -2,
        parry: 'Low',
        other: ['Must be blocked low', 'Special Cancelable', 'Super Cancelable']
      },
      'standing roundhouse': {
        name: 'st. HK',
        damage: 140,
        stun: 13,
        startup: 8,
        active: 5,
        recovery: 18,
        'on block': -5,
        'on hit': -3,
        parry: 'High',
        other: []
      },
      'crouching roundhouse': {
        name: 'cr. HK',
        damage: 130,
        stun: 3,
        startup: 7,
        active: 5,
        recovery: 25,
        'on block': -13,
        'on hit': 'KD',
        parry: 'Low',
        other: []
      },
      'jumping jab': {
        name: 'jp. LP',
        damage: 50,
        stun: 7,
        startup: 4,
        active: 'n/a',
        recovery: 'n/a',
        'on block': '-5 ~ +7',
        'on hit': '-5 ~ +7',
        parry: 'High',
        other: ['Move is active entire time Ryu is in the air']
      },
      'jumping strong': {
        name: 'jp. MP',
        damage: 100,
        stun: 14,
        startup: 4,
        active: 2,
        recovery: 'n/a',
        'on block': '4~10',
        'on hit': '4~10',
        parry: 'High',
        other: []
      },
      'jumping fierce': {
        name: 'jp. HP',
        damage: 140,
        stun: 15,
        startup: 6,
        active: 4,
        recovery: 'n/a',
        'on block': '3~13',
        'on hit': '3~13',
        parry: 'High',
        other: []
      },
      'jumping short (neutral)': {
        name: 'jp. LK',
        damage: 50,
        stun: 5,
        startup: 4,
        active: 19,
        recovery: 'n/a',
        'on block': '-6~7',
        'on hit': '-6~7',
        parry: 'High',
        other: []
      },
      'jumping forward': {
        name: 'jp. MK',
        damage: 90,
        stun: 9,
        startup: 5,
        active: 6,
        recovery: 'n/a',
        'on block': '-2~10',
        'on hit': '-2~10',
        parry: 'High',
        other: []
      },
      'jumping roundhouse': {
        name: 'jp. HK',
        damage: 120,
        stun: 13,
        startup: 6,
        active: 4,
        recovery: 'n/a',
        'on block': '2~13',
        'on hit': '2~13',
        other: ['Diagonal jp. HK has +10 damage and +1 active frame']
      },
      universalOH: {
        name: 'Universal Overhead',
        damage: 40,
        stun: 3,
        startup: 14,
        active: 9,
        recovery: 6,
        'on block': -5,
        'on hit': 0,
        parry: 'High',
        other: []
      }
    },
    'Command Normals': {
      Fmp: {
        name: 'F+MP',
        damage: '60+40',
        stun: '9+7',
        startup: 14,
        active: 12,
        recovery: 9,
        'on block': -1,
        'on hit': 1,
        parry: 'High',
        other: ['Must block standing']
      },
      fhp: {
        name: 'F+HP',
        damage: '70+80',
        stun: '7+7',
        startup: 18,
        active: 6,
        recovery: 13,
        'on block': 2,
        'on hit': 4,
        parry: 'High',
        other: []
      },
      target: {
        name: 'HP -> HK',
        damage: '130+60',
        stun: '13+3',
        startup: 11,
        active: 'n/a',
        recovery: 'n/a',
        'on block': -9,
        'on hit': -7,
        parry: 'High'
      }
    },
    throws: {
      throw: {
        name: 'Throw',
        damage: 120,
        stun: 9,
        range: 24,
        startup: 2,
        active: 1,
        recovery: 21,
        'on hit': 'n/a',
        'on block': 'n/a',
        other: ['Range increases to 40 using Kara F. MP']
      },
      backthrow: {
        name: 'B. Throw',
        damage: 110,
        stun: 15,
        range: 24,
        startup: 2,
        active: 1,
        recovery: 21,
        'on hit': 'n/a',
        'on block': 'n/a',
        other: ['Range increases to 40 using Kara F. MP']
      },
    },
    specials: {
      fireball: {
        name: 'Hadouken',
        input: '↓↘→ + P',
        damage: 60,
        stun: 3,
        startup: 9,
        active: 1,
        recovery: 36,
        'on block': -9,
        'on hit': -8,
        parry: 'High',
        other: ['Super Cancelable']
      },
      dragonpunch: {
        name: 'DP / Shouryuken',
        input: '→↓↘ + P',
        damage: '140/155/170',
        stun: '13/15/17',
        startup: 3,
        active: '11/14/18',
        recovery: '29/34/38',
        'on block': '-14~-38',
        'on hit': 'KD',
        other: ['Super Cancelable']
      },
      tatsu: {
        name: 'Tatsumaki',
        input: '↓↙← + K',
        damage: '130/150/170',
        stun: 15,
        startup: '10/11/11',
        active: '3/10/10',
        recovery: 22,
        'on block': '-12/-8/-11',
        'on hit': 'KD',
        parry: 'High'
      },
      donkey: {
        name: 'Donkey Kick',
        input: '←↙↓↘→ + K',
        damage: '120/140/160',
        stun: 10,
        startup: '10/13/16',
        active: 3,
        recovery: '28/27/26',
        'on block': '-12/-11/-10',
        'on hit': 'KD',
        parry: 'High'
      },
    },
    'EX Moves': {
      Hadouken: {
        name: 'Hadouken',
        input: '→↓↘ + PP',
        guage: 40,
        damage: 120,
        other: ['Super Cancelable'],
        startup: 8,
        active: 1,
        recovery: 36,
        'on block': 0,
        'on hit': 'KD',
        parry: 'High'
      },
      SRK: {
        name: 'Shoryuken',
        input: '→↓↘ + PP',
        guage: 40,
        damage: '110+80',
        other: ['Super Cancelable on first two frames'],
        startup: 2,
        active: 14,
        recovery: 38,
        'on block': -37,
        'on hit': 'KD',
        parry: 'High'
      },
      tatsu: {
        name: 'Tatsumaki',
        input: '↓↙← + KK',
        guage: 40,
        damage: 210,
        startup: 10,
        active: 12,
        recovery: 11,
        'on block': -4,
        'on hit': 'KD',
        parry: 'High'
      },
      donkey: {
        name: 'Donkey Kick',
        input: '←↙↓↘→ + KK',
        guage: 40,
        damage: 120,
        stun: 7,
        startup: 13,
        active: 4,
        recovery: 27,
        'on block': -12,
        'on hit': 'KD',
        parry: 'High'
      },
    },
    supers: {
      sa1: {
        name: 'SA1',
        input: '↓↘→↓↘→ + P',
        damage: 315,
        stun: 0,
        startup: 3,
        active: 1,
        recovery: 49,
        'on block': -12,
        'on hit': 'KD',
        parry: 'High'
      },
      sa2: {
        name: 'SA2',
        input: '↓↘→↓↘→ + P',
        damage: 570,
        stun: 16,
        startup: 1,
        active: 15,
        recovery: 40,
        'on block': -25,
        'on hit': 'KD',
        parry: 'High',
        other: ['Does less damage and stun if hit far']
      },
      sa3: {
        name: 'SA3',
        input: '↓↘→↓↘→ + P',
        damage: '60/120/165/225/270',
        stun: '17/34/48/65/100%',
        startup: '***',
        active: 1,
        recovery: 51,
        'on block': -25,
        'on hit': '***',
        parry: 'High',
        other: ['Has 5 levels of charge. Hold P and spin stick to charge faster']
      },
    }
  }
};
